# Standards: 0.1
---
- name: Enforce defined hostname
  hostname:
    name: "{{ hostname }}"
  tags:
    - hosts

- name: Write hosts config
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags:
    - hosts

...
