# Standards: 1.2
---
- name: Enforce defined hostname
  hostname:
    name: "{{ hostname }}"
  tags:
    - hosts

- name: Write hosts config
  notify:
    - Reload services
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags:
    - hosts

...
