---
- name: Enforce defined hostname
  hostname:
    name: "{{ hostname }}"
  tags:
    - hosts

- name: Write hosts config
  notify:
    - Reload services
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - hosts

...
